[package]
name = "executor_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = { version = "1.0" }
syn = { version = "2.0", features = ["full"] }
proc-macro2 = { version = "1.0" }

[lib]
proc-macro = true
